name: CI Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint

  test:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Run unit tests with coverage
      run: npm run test:unit

  build-frontend:
    name: Build Frontend (Vue 3)
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Build Vue 3 application
      run: npm run build

  build-backend:
    name: Build Backend (.NET)
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore .NET dependencies
      run: dotnet restore
      
    - name: Build .NET projects
      run: dotnet build --no-restore --configuration Release

